# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 13:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(help_text='Enter Book Name', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('library_name', models.CharField(help_text='Enter Library Name', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='books',
            name='library',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_management.Library'),
        ),
    ]
